name: Angular CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - id: setup-chrome
        name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build project
        run: npm run build
